const $=s=>document.querySelector(s), DAYS=['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'];
const STATUS_LABEL={normal:'Normal',attended:'Derse Geldi',absent:'Öğrenci Gelmedi',cancelled:'İptal',makeup:'Telafi'};
const STATUS_UI_TO_DB={normal:'normal',geldi:'attended',gelmedi:'absent',iptal:'cancelled',telafi:'makeup'};
const STATUS_DB_TO_UI={normal:'normal',attended:'geldi',absent:'gelmedi',cancelled:'iptal',makeup:'telafi'};
const cfg=window.DP_CONFIG||{};
const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let user=null,profile=null,teachers=[],students=[],lessons=[],series=[],settings={days:[],breakStart:'13:00',breakEnd:'13:30'},weekStart=startMonday(new Date()),selectedDay=Math.min(new Date().getDay()-1,5),quickFilter='all',realtimeChannel=null;
if(selectedDay<0)selectedDay=0;
function startMonday(d){d=new Date(d);let n=d.getDay()||7;d.setDate(d.getDate()-n+1);d.setHours(0,0,0,0);return d}
function iso(d){let x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function add(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}
function mins(t){let[a,b]=String(t).slice(0,5).split(':').map(Number);return a*60+b}
function hm(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getTeacherName(id){return teachers.find(t=>t.id===id)?.name||''}


async function boot(){let {data:{session}}=await sb.auth.getSession(); if(session) await enterSession(session.user); else showLogin(); sb.auth.onAuthStateChange(async(_,session)=>{if(session&&!user)await enterSession(session.user);if(!session)showLogin()})}
function showLogin(){user=profile=null;login.hidden=false;app.hidden=true}
loginBtn.onclick=async()=>{loginError.textContent='';loginBtn.disabled=true;let {error}=await sb.auth.signInWithPassword({email:loginEmail.value.trim(),password:loginPassword.value});loginBtn.disabled=false;if(error)loginError.textContent='Giriş yapılamadı: e-posta veya şifreyi kontrol et.'};
loginPassword.addEventListener('keydown',e=>{if(e.key==='Enter')loginBtn.click()});
logoutBtn.onclick=async()=>{await sb.auth.signOut();location.reload()};
async function enterSession(authUser){user=authUser;let {data:p,error}=await sb.from('profiles').select('id,full_name,role,active').eq('id',authUser.id).single();if(error||!p||!p.active){await sb.auth.signOut();loginError.textContent='Bu kullanıcı için aktif profil bulunamadı.';return}profile=p;login.hidden=true;app.hidden=false;hello.textContent=`Merhaba ${p.full_name}`;adminBar.hidden=p.role!=='admin';quickFilters.hidden=p.role!=='admin';newBtn.style.display=p.role==='admin'?'':'none';teacherWrap.hidden=p.role!=='admin';await loadAll();subscribeRealtime();render()}
async function loadAll(){await Promise.all([loadTeachers(),loadStudents(),loadSettings()]);await Promise.all([loadLessons(),loadSeries()]);refreshPeopleUI()}
async function loadTeachers(){let {data,error}=await sb.from('teachers').select('id,profile_id,full_name,branch,active').order('full_name');if(error)throw error;teachers=(data||[]).map(t=>({id:t.id,profileId:t.profile_id,name:t.full_name,branch:t.branch,active:t.active}))}
async function loadStudents(){let {data,error}=await sb.from('students').select('id,full_name,instrument,teacher_id,phone,notes,active').eq('active',true).order('full_name');if(error)throw error;students=(data||[]).map(s=>({id:s.id,name:s.full_name,instrument:s.instrument,teacher:s.teacher_id,phone:s.phone||'',note:s.notes||'',active:s.active}))}
async function loadSettings(){let {data,error}=await sb.from('program_settings').select('*').order('day_of_week');if(error)throw error;settings.days=DAYS.map((_,i)=>{let r=(data||[]).find(x=>x.day_of_week===i+1);return {start:String(r?.start_time|| (i===5?'09:00':'10:00')).slice(0,5),end:String(r?.end_time||(i===5?'20:00':'22:00')).slice(0,5)}});let sat=(data||[]).find(x=>x.day_of_week===6);settings.breakStart=String(sat?.break_start||'13:00').slice(0,5);settings.breakEnd=String(sat?.break_end||'13:30').slice(0,5)}
async function loadLessons(){let from=iso(add(weekStart,-1)),to=iso(add(weekStart,7));let {data,error}=await sb.from('lessons').select('id,student_id,teacher_id,instrument,lesson_date,start_time,duration_minutes,status,notes,updated_at,students(full_name)').gte('lesson_date',from).lte('lesson_date',to).order('lesson_date').order('start_time');if(error)throw error;lessons=(data||[]).map(l=>({id:l.id,studentId:l.student_id,student:l.students?.full_name||students.find(s=>s.id===l.student_id)?.name||'Öğrenci',teacher:l.teacher_id,instrument:l.instrument,date:l.lesson_date,time:String(l.start_time).slice(0,5),duration:l.duration_minutes,status:l.status||'normal',notes:l.notes||'',updatedAt:l.updated_at}))}
async function loadSeries(){let to=iso(add(weekStart,7));let {data,error}=await sb.from('lesson_series').select('id,student_id,teacher_id,instrument,day_of_week,start_time,duration_minutes,start_date,end_date,active,created_at').eq('active',true).lte('start_date',to);if(error)throw error;series=data||[]}
function seriesLessons(){let out=[];for(let i=0;i<6;i++){let d=add(weekStart,i),date=iso(d),dow=i+1;for(let s of series){if(s.day_of_week!==dow||date<s.start_date||(s.end_date&&date>s.end_date))continue;let time=String(s.start_time).slice(0,5);let overridden=lessons.some(l=>l.studentId===s.student_id&&l.teacher===s.teacher_id&&l.date===date&&l.time===time);if(overridden)continue;let st=students.find(x=>x.id===s.student_id);out.push({id:`series:${s.id}:${date}`,seriesId:s.id,virtual:true,studentId:s.student_id,student:st?.name||'Öğrenci',teacher:s.teacher_id,instrument:s.instrument,date,time,duration:s.duration_minutes,status:'normal',notes:'',updatedAt:s.created_at})}}return out}
function allWeekLessons(){return lessons.concat(seriesLessons())}
function subscribeRealtime(){if(realtimeChannel)sb.removeChannel(realtimeChannel);realtimeChannel=sb.channel('ders-programi-live').on('postgres_changes',{event:'*',schema:'public',table:'lessons'},async()=>{await loadLessons();render()}).on('postgres_changes',{event:'*',schema:'public',table:'lesson_series'},async()=>{await loadSeries();render()}).on('postgres_changes',{event:'*',schema:'public',table:'students'},async()=>{await loadStudents();ensureStudentList();render()}).on('postgres_changes',{event:'*',schema:'public',table:'teachers'},async()=>{await loadTeachers();refreshPeopleUI();render()}).subscribe()}
function refreshPeopleUI(){let active=teachers.filter(t=>t.active!==false);teacher.innerHTML=active.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');teacherFilter.innerHTML='<option value="all">Tüm öğretmenler</option>'+teacher.innerHTML;studentTeacher.innerHTML=teacher.innerHTML;ensureStudentList()}
function ensureStudentList(){refreshLessonStudents()}
function refreshLessonStudents(selectedId=''){if(!student)return;let tid=teacher?.value||currentTeacherId();let list=students.filter(x=>x.active!==false&&(!tid||x.teacher===tid));student.innerHTML='<option value="">Öğrenci seçin</option>'+list.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(selectedId&&list.some(x=>x.id===selectedId))student.value=selectedId;else if(list.length===1)student.value=list[0].id;syncLessonInstrument()}
function syncLessonInstrument(){let s=students.find(x=>x.id===student?.value);if(s?.instrument)instrument.value=s.instrument}
function currentTeacherId(){return teachers.find(t=>t.profileId===user?.id)?.id||null}
function render(){weekLabel.textContent=`${add(weekStart,0).toLocaleDateString('tr-TR',{day:'numeric',month:'short'})} – ${add(weekStart,5).toLocaleDateString('tr-TR',{day:'numeric',month:'short',year:'numeric'})}`;dayTabs.innerHTML=DAYS.map((d,i)=>`<button data-i="${i}" class="${i===selectedDay?'selected':''}">${d.slice(0,3)}<br>${add(weekStart,i).getDate()}</button>`).join('');dayTabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.i;render()});calendar.innerHTML=innerWidth>=800?DAYS.map((d,i)=>dayHTML(i)).join(''):dayHTML(selectedDay);bindSlots()}
function dayHTML(i){let date=iso(add(weekStart,i)),s=settings.days[i],blocks=[],cur=mins(s.start),end=mins(s.end),bs=mins(settings.breakStart),be=mins(settings.breakEnd);if(i<5){while(cur<end){let next=Math.min(cur+50,end);blocks.push({start:cur,end:next});cur=Math.ceil((cur+1)/60)*60}}else{while(cur<end){if(cur<bs){let next=Math.min(cur+50,bs,end);blocks.push({start:cur,end:next});cur=Math.ceil((cur+1)/60)*60;continue}if(cur>=bs&&cur<be){blocks.push({break:true,start:bs,end:be});cur=be;continue}let next=Math.min(cur+50,end);blocks.push({start:cur,end:next});cur=Math.min(cur+60,end)}}return `<section class="desktopDay"><h3>${DAYS[i]} <small>${add(weekStart,i).getDate()}</small></h3>${blocks.map(b=>slotHTML(date,b)).join('')}</section>`}
function visibleLessons(date){let own=currentTeacherId();return allWeekLessons().filter(l=>{let teacherOk=profile.role==='admin'?(teacherFilter.value==='all'||l.teacher===teacherFilter.value):l.teacher===own;return teacherOk&&l.date===date})}
function slotHTML(date,b){if(b.break)return `<div class="slot"><div class="time">${hm(b.start)}</div><div class="slotbody"><div class="break">☕ MOLA · ${hm(b.start)}–${hm(b.end)}</div></div></div>`;let ls=visibleLessons(date).filter(l=>mins(l.time)>=b.start&&mins(l.time)<b.end);if(profile.role==='admin'){if(quickFilter==='gitar')ls=ls.filter(l=>/gitar/i.test(l.instrument));if(quickFilter==='davul')ls=ls.filter(l=>/davul/i.test(l.instrument))}let showEmpty=!ls.length&&(quickFilter==='all'||quickFilter==='empty');let body=ls.length&&quickFilter!=='empty'?`<div class="lessonstack">${ls.map(l=>`<div class="lesson" data-id="${l.id}"><b>${l.time} · ${esc(l.student)}</b><span>${esc(l.instrument)}</span><small>${esc(getTeacherName(l.teacher))}</small><span class="status">${STATUS_LABEL[l.status]||'Normal'}</span></div>`).join('')}</div>`:showEmpty?`<div class="empty" data-date="${date}" data-time="${hm(b.start)}">＋ BOŞ · ${hm(b.start)}–${hm(b.end)}</div>`:`<div class="filteredout">Bu filtrede ders yok</div>`;return `<div class="slot"><div class="time">${hm(b.start)}</div><div class="slotbody">${body}</div></div>`}
function bindSlots(){document.querySelectorAll('.lesson').forEach(x=>x.onclick=()=>openLesson(x.dataset.id));document.querySelectorAll('.empty').forEach(x=>x.onclick=()=>{if(profile.role==='admin')openLesson(null,x.dataset.date,x.dataset.time)})}
function openLesson(id,date,time){let l=allWeekLessons().find(x=>x.id===id);if(profile.role!=='admin'){let d=dlg;formTitle.textContent=l?.student||'Ders';lessonForm.innerHTML=`<div class="dialogpad"><h2>${esc(l?.student||'Ders')}</h2><p><b>${esc(l?.instrument||'')}</b></p><p>${l?.date||''} · ${l?.time||''}</p><p>Durum: ${STATUS_LABEL[l?.status]||'Normal'}</p>${l?.notes?`<p>Not: ${esc(l.notes)}</p>`:''}<p><small>${esc(getTeacherName(l?.teacher))}</small></p><div style="text-align:right;margin-top:18px"><button type="button" id="teacherLessonClose">Kapat</button></div></div>`;d.querySelector('#teacherLessonClose').onclick=()=>d.close();d.showModal();return}formTitle.textContent=l?'Dersi Düzenle':'Yeni Ders';lessonId.value=l?.id||'';teacher.value=l?.teacher||teachers.find(t=>t.active!==false)?.id||'';refreshLessonStudents(l?.studentId||'');instrument.value=l?.instrument||students.find(s=>s.id===student.value)?.instrument||'Elektro Gitar';$('#date').value=l?.date||date||iso(new Date());$('#time').value=l?.time||time||'10:00';duration.value=l?.duration||50;repeat.checked=!!l?.virtual;repeat.disabled=!!l;notes.value=l?.notes||'';$('#status').value=STATUS_DB_TO_UI[l?.status||'normal'];deleteBtn.style.visibility=(l&&!l.virtual)?'visible':'hidden';lessonAudit.textContent=l?.updatedAt?`Son değişiklik: ${new Date(l.updatedAt).toLocaleString('tr-TR')}`:'';dlg.showModal()}
lessonForm.onsubmit=async e=>{e.preventDefault();if(profile.role!=='admin')return;let existing=allWeekLessons().find(x=>x.id===lessonId.value);let st=students.find(s=>s.id===student.value);if(!st)return alert('Lütfen kayıtlı bir öğrenci seç.');let date=$('#date').value,time=$('#time').value,status=STATUS_UI_TO_DB[$('#status').value];let error;if(!existing&&repeat.checked){let d=new Date(date+'T12:00:00');let dow=d.getDay();if(dow<1||dow>6)return alert('Pazar günü ders oluşturulamaz.');let seriesPayload={student_id:st.id,teacher_id:teacher.value,instrument:instrument.value,day_of_week:dow,start_time:time,duration_minutes:+duration.value,start_date:date,active:true,created_by:user.id};({error}=await sb.from('lesson_series').insert(seriesPayload));if(!error&&status!=='normal'){let p={student_id:st.id,teacher_id:teacher.value,instrument:instrument.value,lesson_date:date,start_time:time,duration_minutes:+duration.value,status,notes:notes.value.trim()||null,created_by:user.id,updated_by:user.id};({error}=await sb.from('lessons').insert(p))}}else{let payload={student_id:st.id,teacher_id:teacher.value,instrument:instrument.value,lesson_date:date,start_time:time,duration_minutes:+duration.value,status,notes:notes.value.trim()||null,updated_by:user.id};if(existing&&!existing.virtual){({error}=await sb.from('lessons').update(payload).eq('id',existing.id))}else{payload.created_by=user.id;({error}=await sb.from('lessons').insert(payload))}}if(error)return alert(error.message);dlg.close();await Promise.all([loadLessons(),loadSeries()]);render()};
cancel.onclick=()=>dlg.close();deleteBtn.onclick=async()=>{if(profile.role!=='admin'||!lessonId.value)return;if(!confirm('Bu dersi silmek istiyor musun?'))return;let {error}=await sb.from('lessons').delete().eq('id',lessonId.value);if(error)return alert(error.message);dlg.close();await loadLessons();render()};
newBtn.onclick=()=>openLesson(null,iso(add(weekStart,selectedDay)),'10:00');prev.onclick=async()=>{weekStart=add(weekStart,-7);await Promise.all([loadLessons(),loadSeries()]);render()};next.onclick=async()=>{weekStart=add(weekStart,7);await Promise.all([loadLessons(),loadSeries()]);render()};today.onclick=async()=>{weekStart=startMonday(new Date());await Promise.all([loadLessons(),loadSeries()]);render()};teacherFilter.onchange=render;
settingsBtn.onclick=()=>{daySettings.innerHTML=DAYS.map((d,i)=>`<div class="settingrow"><b>${d.slice(0,3)}</b><label>Başlangıç<input type="time" data-i="${i}" data-k="start" value="${settings.days[i].start}"></label><label>Bitiş<input type="time" data-i="${i}" data-k="end" value="${settings.days[i].end}"></label></div>`).join('');breakStart.value=settings.breakStart;breakEnd.value=settings.breakEnd;settingsDlg.showModal()};settingsCancel.onclick=()=>settingsDlg.close();settingsForm.onsubmit=async e=>{e.preventDefault();daySettings.querySelectorAll('input').forEach(x=>settings.days[+x.dataset.i][x.dataset.k]=x.value);settings.breakStart=breakStart.value;settings.breakEnd=breakEnd.value;for(let i=0;i<6;i++){if(mins(settings.days[i].start)>=mins(settings.days[i].end))return alert(DAYS[i]+' için bitiş saati başlangıçtan sonra olmalı.')}if(mins(settings.breakStart)>=mins(settings.breakEnd))return alert('Cumartesi mola bitişi başlangıçtan sonra olmalı.');let sat=settings.days[5];if(mins(settings.breakStart)<mins(sat.start)||mins(settings.breakEnd)>mins(sat.end))return alert('Cumartesi molası çalışma saatlerinin içinde olmalı.');let rows=settings.days.map((d,i)=>({day_of_week:i+1,start_time:d.start,end_time:d.end,break_start:i===5?settings.breakStart:null,break_end:i===5?settings.breakEnd:null,slot_minutes:50,updated_at:new Date().toISOString()}));let {error}=await sb.from('program_settings').upsert(rows,{onConflict:'day_of_week'});if(error)return alert(error.message);await loadSettings();settingsDlg.close();render()};
studentsBtn.onclick=()=>openStudents();studentsClose.onclick=()=>studentsDlg.close();
function openStudents(){studentsTitle.textContent=profile.role==='admin'?'Öğrenciler':'Öğrencilerim';addStudentBtn.style.display=profile.role==='admin'?'':'none';let own=currentTeacherId(),mine=students.filter(x=>profile.role==='admin'||x.teacher===own);studentList.innerHTML=mine.length?mine.map(x=>`<div class="studentitem" data-id="${x.id}"><b>${esc(x.name)}</b><br><small>${esc(x.instrument)} · ${esc(getTeacherName(x.teacher))}${x.phone?' · '+esc(x.phone):''}</small></div>`).join(''):'Henüz öğrenci yok.';studentList.querySelectorAll('.studentitem').forEach(x=>x.onclick=()=>openStudent(x.dataset.id));studentsDlg.showModal()}
addStudentBtn.onclick=()=>openStudent();
function openStudent(id){let x=students.find(s=>s.id===id);studentRecordId.value=x?.id||'';studentName.value=x?.name||'';studentInstrument.value=x?.instrument||'Elektro Gitar';refreshPeopleUI();studentTeacher.value=x?.teacher||teachers.find(t=>t.active!==false)?.id||'';studentPhone.value=x?.phone||'';studentNote.value=x?.note||'';studentDelete.style.visibility=(x&&profile.role==='admin')?'visible':'hidden';[studentName,studentInstrument,studentTeacher,studentPhone,studentNote].forEach(el=>el.disabled=profile.role!=='admin');studentForm.querySelector('button.primary').style.display=profile.role==='admin'?'':'none';let hist=x?allWeekLessons().filter(l=>l.studentId===x.id).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)):[];studentHistory.innerHTML=hist.length?hist.map(l=>`<div class="historyitem"><b>${new Date(l.date+'T00:00').toLocaleDateString('tr-TR')} · ${l.time}</b><br><small>${STATUS_LABEL[l.status]||'Normal'}${l.notes?' · '+esc(l.notes):''}</small></div>`).join(''):'Bu hafta için ders geçmişi yok.';studentDlg.showModal()}
studentForm.onsubmit=async e=>{e.preventDefault();if(profile.role!=='admin')return;let payload={full_name:studentName.value.trim(),instrument:studentInstrument.value,teacher_id:studentTeacher.value,phone:studentPhone.value.trim()||null,notes:studentNote.value.trim()||null,active:true};let error;if(studentRecordId.value)({error}=await sb.from('students').update(payload).eq('id',studentRecordId.value));else({error}=await sb.from('students').insert(payload));if(error)return alert(error.message);await loadStudents();studentDlg.close();studentsDlg.close();openStudents()};studentCancel.onclick=()=>studentDlg.close();studentDelete.onclick=async()=>{if(!studentRecordId.value)return;let {error}=await sb.from('students').update({active:false}).eq('id',studentRecordId.value);if(error)return alert(error.message);await loadStudents();studentDlg.close();studentsDlg.close();openStudents()};
teachersBtn.onclick=()=>{teacherList.innerHTML=teachers.map(t=>`<div class="teacheritem" data-id="${t.id}"><b>${esc(t.name)}</b><br><small>${esc(t.branch||'Branş belirtilmedi')} · ${t.active===false?'Pasif':'Aktif'} · ${t.profileId?'Giriş hesabı var':'Giriş hesabı yok'}</small></div>`).join('');teacherList.querySelectorAll('.teacheritem').forEach(x=>x.onclick=()=>openTeacher(x.dataset.id));teachersDlg.showModal()};teachersClose.onclick=()=>teachersDlg.close();addTeacherBtn.onclick=()=>openTeacher();
function openTeacher(id){let t=teachers.find(x=>x.id===id);teacherRecordId.value=t?.id||'';$('#teacherName').value=t?.name||'';teacherBranch.value=t?.branch||'Elektro Gitar';teacherActive.checked=t?.active!==false;teacherDelete.style.visibility=t?'visible':'hidden';teacherEmail.value='';teacherPassword.value='';let hasAccount=!!t?.profileId;teacherLoginFields.hidden=hasAccount;teacherAccountStatus.hidden=!hasAccount;teacherSaveBtn.textContent=hasAccount?'Kaydet':'Hesap Oluştur';teacherDlg.showModal()}
async function edgeErrorMessage(error){let msg=error?.message||'Bilinmeyen hata';try{let d=await error.context.json();if(d?.error)msg=d.error}catch{}return msg}
teacherForm.onsubmit=async e=>{e.preventDefault();if(profile.role!=='admin')return;let t=teachers.find(x=>x.id===teacherRecordId.value),name=$('#teacherName').value.trim(),branch=teacherBranch.value,active=teacherActive.checked;if(!name)return alert('Öğretmen adı zorunlu.');if(t?.profileId){let {error}=await sb.from('teachers').update({full_name:name,branch,active}).eq('id',t.id);if(error)return alert(error.message)}else{let email=teacherEmail.value.trim(),password=teacherPassword.value;if(!email)return alert('Öğretmenin e-posta adresini gir.');if(password.length<6)return alert('Şifre en az 6 karakter olmalı.');teacherSaveBtn.disabled=true;teacherSaveBtn.textContent='Oluşturuluyor…';let {data,error}=await sb.functions.invoke('create-teacher-user',{body:{full_name:name,branch,email,password,teacher_id:t?.id||null}});teacherSaveBtn.disabled=false;teacherSaveBtn.textContent='Hesap Oluştur';if(error)return alert('Hesap oluşturulamadı: '+await edgeErrorMessage(error));if(!data?.success)return alert('Hesap oluşturulamadı: '+(data?.error||'Bilinmeyen hata'));if(!active){await loadTeachers();let created=teachers.find(x=>x.profileId===data.user_id);if(created)await sb.from('teachers').update({active:false}).eq('id',created.id)}alert('Öğretmen giriş hesabı oluşturuldu.')}await loadTeachers();refreshPeopleUI();teacherDlg.close();teachersDlg.close();teachersBtn.click()};teacherCancel.onclick=()=>teacherDlg.close();teacherDelete.onclick=async()=>{let id=teacherRecordId.value;if(!id)return;let {error}=await sb.from('teachers').update({active:false}).eq('id',id);if(error)return alert(error.message);await loadTeachers();refreshPeopleUI();teacherDlg.close();teachersDlg.close();teachersBtn.click()};
function auditSummary(a){
  const old=a.old_data||{}, neu=a.new_data||{};
  const action={INSERT:'Ders eklendi',UPDATE:'Ders değiştirildi',DELETE:'Ders silindi'}[a.action]||a.action;
  if(a.action==='UPDATE'){
    const parts=[];
    if(old.status!==neu.status) parts.push(`Durum: ${STATUS_LABEL[old.status]||old.status||'-'} → ${STATUS_LABEL[neu.status]||neu.status||'-'}`);
    if(String(old.lesson_date||'')!==String(neu.lesson_date||'')) parts.push(`Tarih: ${old.lesson_date||'-'} → ${neu.lesson_date||'-'}`);
    if(String(old.start_time||'').slice(0,5)!==String(neu.start_time||'').slice(0,5)) parts.push(`Saat: ${String(old.start_time||'-').slice(0,5)} → ${String(neu.start_time||'-').slice(0,5)}`);
    if(old.teacher_id!==neu.teacher_id) parts.push(`Öğretmen: ${getTeacherName(old.teacher_id)||'Eski öğretmen'} → ${getTeacherName(neu.teacher_id)||'Yeni öğretmen'}`);
    if(old.student_id!==neu.student_id){let os=students.find(x=>x.id===old.student_id)?.name||'Eski öğrenci', ns=students.find(x=>x.id===neu.student_id)?.name||'Yeni öğrenci';parts.push(`Öğrenci: ${os} → ${ns}`)}
    if(old.instrument!==neu.instrument) parts.push(`Enstrüman: ${old.instrument||'-'} → ${neu.instrument||'-'}`);
    if((old.notes||'')!==(neu.notes||'')) parts.push('Not değiştirildi');
    return parts.length?parts.join(' · '):action;
  }
  let d=neu.student_id?neu:old, studentName=students.find(x=>x.id===d.student_id)?.name||'Ders';
  return `${action}: ${studentName}${d.lesson_date?' · '+d.lesson_date:''}${d.start_time?' · '+String(d.start_time).slice(0,5):''}`;
}
auditBtn.onclick=async()=>{
  let {data,error}=await sb.from('change_log').select('created_at,action,table_name,record_id,changed_by,old_data,new_data').eq('table_name','lessons').order('created_at',{ascending:false}).limit(200);
  if(error){auditList.innerHTML='Geçmiş okunamadı: '+esc(error.message);auditDlg.showModal();return}
  let ids=[...new Set((data||[]).map(a=>a.changed_by).filter(Boolean))], names={};
  if(ids.length){let {data:ps}=await sb.from('profiles').select('id,full_name').in('id',ids);(ps||[]).forEach(p=>names[p.id]=p.full_name)}
  auditList.innerHTML=(data||[]).length?(data||[]).map(a=>`<div class="historyitem"><b>${esc(auditSummary(a))}</b><br><small>${new Date(a.created_at).toLocaleString('tr-TR')} · ${esc(names[a.changed_by]||'Yönetici')}</small></div>`).join(''):'Henüz değişiklik yok.';
  auditDlg.showModal()
};auditClose.onclick=()=>auditDlg.close();
document.querySelectorAll('#quickFilters button').forEach(b=>b.onclick=()=>{quickFilter=b.dataset.filter;document.querySelectorAll('#quickFilters button').forEach(x=>x.classList.toggle('selected',x===b));render()});
window.addEventListener('resize',()=>{if(profile)render()});
boot().catch(e=>{console.error(e);loginError.textContent='Uygulama başlatılamadı: '+e.message});

teacher.addEventListener('change',()=>refreshLessonStudents());
student.addEventListener('change',syncLessonInstrument);
